apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: url-shortner-ns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      imagePullSecrets:
        - name: redis-key
      initContainers:
      - name: fix-permissions
        image: alpine:latest 
        command: ["sh", "-c", "chmod -R 777 /data"]
        securityContext:
          runAsUser: 0  
        volumeMounts:
          - name: redis-data
            mountPath: /data
      containers:
      - name: redis-cache-container
        image: dhi.io/redis:8-alpine
        ports:
        - containerPort: 6379
        command: ["redis-server"]
        args: ["--requirepass", "$(REDIS_PASSWORD)", "--appendonly", "yes"]
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: url-shortner-secrets
              key: REDIS_PASSWORD
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
